apiVersion: apps/v1
kind: Deployment
metadata:
  name: job_portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job_portal
  template:
    metadata:
      labels:
        app: job_portal
    spec:
      containers:
      - name: job_portal
        image: mohit3252/job_portal
        ports:
        - containerPort: 8000
