apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-portal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: job-portal
  template:
    metadata:
      labels:
        app: job-portal
    spec:
      containers:
      - name: job-portal
        image: mohit3252/job-portal
        ports:
        - containerPort: 8000
