# Generated by Django 3.2.5 on 2021-07-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210702_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
