# Generated by Django 3.2.5 on 2021-07-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210706_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
