# Generated by Django 3.2.5 on 2021-07-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
