# Generated by Django 3.2.5 on 2021-08-02 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='image',
            new_name='logo',
        ),
    ]
