# Generated by Django 3.2.5 on 2021-08-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20210802_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='image',
            field=models.FileField(max_length=60, null=True, upload_to=''),
        ),
    ]
