# Generated by Django 3.2.5 on 2021-08-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_recruiter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('apply_date', models.DateField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.job')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='job.student')),
            ],
        ),
    ]
